// Code generated by "enumer --type=Job --linecomment --extramethod --output=job_enum.go"; DO NOT EDIT.

package cnst

import (
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Job_Demo-1]
}

const _Job_name = "DEMO"

var _Job_index = [...]uint8{0, 4}

func (i Job) String() string {
	i -= 1
	if i >= Job(len(_Job_index)-1) {
		return "Job(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Job_name[_Job_index[i]:_Job_index[i+1]]
}

var _Job_values = []Job{1}

var _Job_name_to_value_map = map[string]Job{
	_Job_name[0:4]: 1,
}

// JobFromStr 将字符串转换成 Job 枚举类型；如果传入的不是有效的枚举值，返回 0 值。
func JobFromStr(s string) Job {
	if val, ok := _Job_name_to_value_map[s]; ok {
		return val
	}
	return 0
}

// JobFromStrE 将字符串转换成 Job 枚举类型；如果传入的不是有效的枚举值，抛出错误。
func JobFromStrE(s string) (Job, error) {
	if val, ok := _Job_name_to_value_map[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("not valid enum: %s", s)
}

// JobFromInt 将int值转换成 Job 枚举类型；如果传入的不是有效的枚举值，返回 0 值。
func JobFromInt(i int) Job {
	if _JobIsValid(i) {
		return Job(i)
	}
	return 0
}

// JobFromIntE 将int值转换成 Job 枚举类型；如果传入的不是有效的枚举值，抛出错误。
func JobFromIntE(i int) (Job, error) {
	if _JobIsValid(i) {
		return Job(i), nil
	}
	return 0, fmt.Errorf("not valid enum: %d", i)
}

// JobFromInt64 将int64转换成 Job 枚举类型；如果传入的不是有效的枚举值，返回 0 值。
func JobFromInt64(i int64) Job {
	return JobFromInt(int(i))
}

// JobFromInt64E 将int64转换成 Job 枚举类型；如果传入的不是有效的枚举值，抛出错误。
func JobFromInt64E(i int64) (Job, error) {
	return JobFromIntE(int(i))
}

// IsValid 判断该枚举值是否有效。
func (i Job) IsValid() bool {
	return _JobIsValid(int(i))
}

// Check 校验该枚举值是否有效，如果无效，抛出错误。
func (i Job) Check() (err error) {
	if is := i.IsValid(); !is {
		err = fmt.Errorf("not valid enum: %v", i)
	}
	return err
}

type JobSlice []Job

// Has 判断给定枚举值是否在当前数组中。
func (inst JobSlice) Has(i Job) bool {
	for _, v := range inst {
		if i == v {
			return true
		}
	}
	return false
}

// Strings 将枚举数组转换为字符串数组。
func (inst JobSlice) Strings() []string {
	ss := make([]string, len(inst))
	for i, v := range inst {
		ss[i] = v.String()
	}
	return ss
}

// JobValues 返回 Job 类型的所有的枚举值。
func JobValues() JobSlice {
	return _Job_values
}

// JobFromStrs 将字符串数组转换成 Job 枚举数组；如果传入的字符串不是有效的枚举值，抛出错误。
func JobFromStrs(ss []string) (JobSlice, error) {
	es := make(JobSlice, 0, len(ss))
	for _, s := range ss {
		v, err := JobFromStrE(s)
		if err != nil {
			return nil, err
		}
		es = append(es, v)
	}
	return es, nil
}

// JobFromInts 将int数组转换成 Job 枚举数组；如果传入的不是有效的枚举值，抛出错误。
func JobFromInts(ints []int) (JobSlice, error) {
	es := make(JobSlice, 0, len(ints))
	for _, i := range ints {
		v, err := JobFromIntE(i)
		if err != nil {
			return nil, err
		}
		es = append(es, v)
	}
	return es, nil
}

// JobFromInt64s 将int64数组转换成 Job 枚举数组；如果传入的不是有效的枚举值，抛出错误。
func JobFromInt64s(int64s []int64) (JobSlice, error) {
	ints := make([]int, 0, len(int64s))
	for _, i := range int64s {
		ints = append(ints, int(i))
	}
	return JobFromInts(ints)
}

// _JobIsValid 判断 int 是否是有效的枚举值
func _JobIsValid(i int) bool {
	for _, v := range _Job_values {
		if i == int(v) {
			return true
		}
	}
	return false
}
