server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s

data:
  log:
    level: info # debug info warn error
  timezone:
    location: "Asia/Shanghai"
    offset: 8*3600
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=true&loc=Local&charset=utf8mb4
  redis:
    addr: 127.0.0.1:6379
    pwd:
    tls: false
    read_timeout: 0.2s
    write_timeout: 0.2s
  registrar:
  # endpoints: [ "127.0.0.1:2379" ] # with etcd
  mq:
  # driver: rabbitmq
  # source: "amqp://root:pwd@127.0.0.1:5672/"
  # exchangeMultiLevelScore: core-multi-level-score

business:
  name: demo