// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/night-sword/kratos-layout/cmd/internal"
	"github.com/night-sword/kratos-layout/internal/conf"
	"github.com/night-sword/kratos-layout/internal/server"
	"github.com/night-sword/kratos-layout/internal/service"
)

// Injectors from wire.go:

func wireApp(arg []kratos.Option, bootstrap *conf.Bootstrap) (*kratos.App, func(), error) {
	health := service.NewHealth()
	grpcServer := server.NewGRPCServer(bootstrap, health)
	httpServer := server.NewHTTPServer(bootstrap, health)
	servers := newServers(grpcServer, httpServer)
	app := internal.NewKratos(arg, servers, bootstrap)
	return app, func() {
	}, nil
}
